version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - run: |
          sudo service docker start; \
          sudo docker build -t test-nginx .
      - run:
          name: Run tests
          command: dgoss run -p 8080:80 test-nginx


